appName: fastapi-example
port: 80
namespace: prod
replicaCount: 1
configmap:
  name: myhelmapp-configmap-v1
  data:
    CUSTOM_HEADER: "This app was deployed with helm!"
image:
  name: fastapi_example
  tag: latest
  pullPolicy: IfNotPresent
